name: Adoption / Use Case
description: Tell us your Adoption / Use Case Story
title: "[Adoption]: <Company> - <Title>"
labels: ["community"]
assignees:
  - mauromorales
body:
  - type: markdown
    attributes:
      value: |
        Thank you for choosing Kairos and its community!
  - type: input
    id: name
    attributes:
      label: Person of contact's full name
      description: Who are you?
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: GH username, LinkedIn, Slack, e-mail, other.
      description: How can we contact you?
    validations:
      required: true
  - type: input
    id: company
    attributes:
      label: Company or Organization Name (optional)
      description: Name of the company or organization you are working for
      placeholder: "ACME Inc."
    validations:
      required: false
  - type: input
    id: company-contact
    attributes:
      label: Link to your company or organization Name (optional)
      description: URL to a website, GH org, or other
      placeholder: "www.example.com"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: What is your project about?
      description: In your own words, how would you describe your project?
    validations:
      required: true
  - type: textarea
    id: story
    attributes:
      label: Your Story (optional but recommended. Stories can be very powerful!)
      description: What is your story about Kairos? Where did you use it and how did it help you?
    validations:
      required: false
  - type: textarea
    id: improvements
    attributes:
      label: Improvements (optional)
      description: What could be improved in Kairos?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        If you want to also be displayed on the kairos.io website, please upload your project/company artwork.
  - type: checkboxes
    id: checks
    attributes:
      label: Please check the following
      description: By submitting this issue, you state that you are allowed to share this story and that you agree that we can use it for project promotion purposes.
      options:
        - label: I am allowed to share this information with Kairos
          required: true
        - label: I agree that this information can be used for project promotion purposes
          required: true
        - label: I agree that the artwork (if uploaded) can be used in the Kairos website or promotional material
          required: false
