name: Adoption / Use Case
description: Tell us your Adoption / Use Case Story
title: "[Adoption]: <Company> - <Title>"
labels: ["community"]
assignees:
  - kairos-io/maintainers
body:
  - type: markdown
    attributes:
      value: |
        Thank you for telling us your story about Kairos!
  - type: input
    id: company
    attributes:
      label: Company Name (optional)
      description: Name of the company you are working for
      placeholder: "ACME Inc."
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Username on the Kairos Slack / Matrix, e-mail, etc.
      description: Tell us how we can contact you
    validations:
      required: true
  - type: textarea
    id: story
    attributes:
      label: Your Story
      description: What is your story about Kairos? Where did you use it and how did it help you?
    validations:
      required: true
  - type: textarea
    id: improvements
    attributes:
      label: Improvements
      description: What could be improved in Kairos?
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Please check the following
      description: By submitting this issue, you state that you are allowed to share this story and that you agree that we can use it for project promotion purposes.
      options:
        - label: I am allowed to share this story
          required: true
        - label: I agree that this story can be used for project promotion purposes
        - label: I already added me and my company in the [ADOPTERS](https://github.com/kairos-io/community/blob/main/ADOPTERS.md) file
          required: true